# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: gha-debian13-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          uname -a
          uname -r
          lsb_release -a

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: '3.13.7'

      - name: Check Python
        run: |
          python --version

      - name: Setup C/C++ Compiler
        # You may pin to the exact commit or the version.
        # uses: rlalik/setup-cpp-compiler@f39db50a7fd04bfd65ce41e8fec0ac185ae59dfb
        uses: rlalik/setup-cpp-compiler@v1.2
        with:
          # Compiler to install
          compiler: 'gcc-latest'

      - name: Check GCC
        run: |
          gcc --version
      
      - name: Build C++ program
        run: |
          g++ -std=c++17 -Wall -Wextra -O2 main.cpp -o app

      - name: Run C++ program
        run: |
          ./app
          
